In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b
print(result) 

[5 7 9]


In [13]:
import numpy as np
value=np.array([2,4,8])
value%=2
print(value)

[0 0 0]


In [12]:
import numpy as np
c=np.array([2,4])
d=c**2
print(d)

[ 4 16]


In [15]:
import numpy as np
e=np.array([2,1])
f=np.tan(e)
print(f)

[-2.18503986  1.55740772]


In [17]:
g = np.array([[1, 2], [3, 4]])
h = np.array([5, 6])
result = g * h
print(result) 

[[ 5 12]
 [15 24]]


In [22]:
import numpy as np
k=np.array([1,2,3,4,5])
result=np.median(k)

print(result)

3.0


In [23]:
import pandas as pd
data = {'Name': ['John', 'Mary', 'David'],
        'Age': [25, 31, 42],
        'Country': ['USA', 'Canada', 'UK']}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0   John   25     USA
1   Mary   31  Canada
2  David   42      UK


In [33]:
import pandas as pd
data={'name':['cravin','sanajy',None,'DHARANI'],'age':[12,23,45,None]}
cravin=pd.DataFrame(data)
print(cravin)

      name   age
0   cravin  12.0
1   sanajy  23.0
2     None  45.0
3  DHARANI   NaN


In [25]:
import pandas as pd

data = {'Name': ['John', 'Mary', None, 'David'],
        'Age': [25, 31, 42, None]}
df = pd.DataFrame(data)
print(df)

    Name   Age
0   John  25.0
1   Mary  31.0
2   None  42.0
3  David   NaN


In [37]:
import pandas as pd
data = {'Name': ['John', 'Mary', 'David'],
        'Age': [25, 31, 42]}
df = pd.DataFrame(data)
print(df.query('Age > 30'))

    Name  Age
1   Mary   31
2  David   42


In [42]:
import pandas as ap
details = {'Name': ['John', 'Mary', 'David'],
        'Age': [25, 31, 42],
        'Country': ['USA', 'Canada', 'UK']}
df = ap.DataFrame(details)
print(df.pivot_table(index='Country', values='Age'))

          Age
Country      
Canada   31.0
UK       42.0
USA      25.0


In [41]:
import pandas as pd
value = {'Name': ['John', 'Mary', 'David'],
        'Age': [25, 31, 42],
        'Country': ['USA', 'Canada', 'UK']}
df = pd.DataFrame(value)
print(df.groupby('Name')['Age'].mean())

Name
David    42.0
John     25.0
Mary     31.0
Name: Age, dtype: float64


In [1]:
##scipy

from scipy import cluster

C:\Users\Arun\AppData\Local\Temp\ipykernel_11552\3841310315.py:3: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 2.3.0)
  from scipy import cluster


ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [2]:
help(cluster)

NameError: name 'cluster' is not defined

In [3]:
from scipy import special
a = special.exp10(2)
print(a)

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [5]:
import scipy

In [6]:
from scipy import special
a = special.exp10(2)
print(a)

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [7]:
import scipy


In [8]:
from scipy import cluster 

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [9]:
from scipy import constants
print(constants.liter)

0.001


In [10]:
import scipy
print(scipy.__version__)

1.13.1


In [25]:
pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [26]:
##statsmodels
import statsmodels.api as sm
from sklearn import datasets
import numpy as np
import pandas as pd


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Arun\anaconda3\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Arun\anaconda3\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\Arun\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Arun\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Arun\anaconda3\Lib\site-packages

ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.



ImportError: numpy.core.multiarray failed to import